### PR TITLE
Update flexible_bottom_sheet.dart

### PR DESCRIPTION
**Pull request by aprzedecki**
Fix for the Flutter 3.3.0 update

### CODE REVIEW

**Comment by aprzedecki** [comment]
Would be great if some of you guys release and publish this fix cc @MbIXjkee @KristinaZoteva 
Many people have this issue after update https://github.com/surfstudio/flutter-bottom-sheet/issues/57

**Comment by aprzedecki** [comment]
@dshevchenkoo @dkrutskikh maybe you guys can help ?

**Review by waslost0 — DISMISSED** [review]

**Comment by AppetiteTeam** [comment]
same

**Comment by nicejhkim** [comment]
@aprzedecki 
With your commit, headerBuilder is executed with offset 0 not initHeight when showStickyFlexibleBottomSheet() is called.

image

I think currentExtent should be set to widget.initHeight instead of 0.
`currentExtent: _controller.isAttached ? _controller.size : widget.initHeight`

**Comment by aprzedecki** [comment]
> @aprzedecki With your commit, headerBuilder is executed with offset 0 not initHeight when showStickyFlexibleBottomSheet() is called.
> 
> image
> 
> I think currentExtent should be set to widget.initHeight instead of 0. `currentExtent: _controller.isAttached ? _controller.size : widget.initHeight`

controller is attaching within milliseconds, so I am afraid this would cause some flashing

**Comment by dshevchenkoo** [comment]
We'll try to fix it this week

**Comment by zaharovroman** [comment]
> > @aprzedecki With your commit, headerBuilder is executed with offset 0 not initHeight when showStickyFlexibleBottomSheet() is called.
> > image
> > I think currentExtent should be set to widget.initHeight instead of 0. `currentExtent: _controller.isAttached ? _controller.size : widget.initHeight`
> 
> controller is attaching within milliseconds, so I am afraid this would cause some flashing

As @nicejhkim has already answered, currentExtent should be set to widget.initHeight
`
- currentExtent: _controller.size,
+ currentExtent: _controller.isAttached
+   ? _controller.size
+   : widget.initHeight,
`

**Comment by zaharovroman** [comment]
> > @aprzedecki With your commit, headerBuilder is executed with offset 0 not initHeight when showStickyFlexibleBottomSheet() is called.
> > image
> > I think currentExtent should be set to widget.initHeight instead of 0. `currentExtent: _controller.isAttached ? _controller.size : widget.initHeight`
> 
> controller is attaching within milliseconds, so I am afraid this would cause some flashing

As @nicejhkim has already answered, currentExtent should be set to widget.initHeight
```dart
- currentExtent: _controller.size,
+ currentExtent: _controller.isAttached
+   ? _controller.size
+   : widget.initHeight,
```

**Comment by aprzedecki** [comment]
> > > @aprzedecki With your commit, headerBuilder is executed with offset 0 not initHeight when showStickyFlexibleBottomSheet() is called.
> > > image
> > > I think currentExtent should be set to widget.initHeight instead of 0. `currentExtent: _controller.isAttached ? _controller.size : widget.initHeight`
> > 
> > 
> > controller is attaching within milliseconds, so I am afraid this would cause some flashing
> 
> As @nicejhkim has already answered, currentExtent should be set to widget.initHeight
> 
> ```dart
> - currentExtent: _controller.size,
> + currentExtent: _controller.isAttached
> +   ? _controller.size
> +   : widget.initHeight,
> ```

I agree. Modified the PR.

**Comment by dshevchenkoo** [comment]
@aprzedecki 
Thank you for your contribution to the development of the package [bottom_sheet](https://pub.dev/packages/bottom_sheet)
We solved the problem under another pr https://github.com/surfstudio/flutter-bottom-sheet/pull/65

surf team

**Comment by aprzedecki** [comment]
Great. Can you also publish the fix to pub.dev ?

**Comment by dshevchenkoo** [comment]
Oh sure
There are a few more tasks that we want to complete before publication, we will try to do it this week

**Pull request closed without merging**
